- Linked List/linklist.cpp
Please accept my pull request as I am participating in hacktoberfest
> linklist added

- array/JAVA/bar_chart_array.java
- array/JAVA/binary_search.java
- array/JAVA/ceil_floor_array.java
- array/JAVA/difference_array.java
- array/JAVA/find_element_array.java
- array/JAVA/intro_array.java
- array/JAVA/inverse_array.java
- array/JAVA/reverse_array.java
- array/JAVA/rotate_array.java
- array/JAVA/span_array.java
- array/JAVA/subarrays_of_array.java
- array/JAVA/sum_array.java
some problems added in separate JAVA section. JAVA problems based on arrays(revers an array , rotate an arrays)
> added JAVA problems based on arrays

- graphs/adjacencylist.cpp
- graphs/counttheconnected.cpp
- graphs/cycledetectionDGdfs.cpp
- graphs/cycledetectionUGbfs.cpp
- graphs/cycledetectionUGdfs.cpp
- graphs/cycledetectionusingkhanalgo.cpp
- graphs/dijkstra.cpp
- graphs/primsalgo1.cpp
- graphs/primsalgooptimised.cpp
- graphs/shortedpathinunweightedgraph.cpp
- graphs/shortestpathDAG.cpp
- graphs/topologicalsortbfs.cpp
- graphs/topologicalsortdfs.cpp
- graphs/traversalbfs.cpp
- graphs/traversaldfs.cpp
1.Graph traversal algorithm - dfs and bfs
2. Cycle detection in directed graphs
3. Cycle detection in undirected graph
4.Count the connected component of graph
5.Topological sort
6. Cycle detection using Kahn's algorithm
7.Dijkstra Algorithm
8.Prims Algorithm
9. Shortest path problems
> added graphs

- Dynamic Programming/Max_profit.cpp
Added code for  dynamic programming problem which includes greedy + dynamic approach
> Maximum Profit in Job Scheduling

- String/Longest_Palindromic_String.cpp
One of the most common Question of DSA
> Added Longest Palindromic String

- Modified Bubble sort.c
> Create Modified Bubble sort.c

- Binary search tree/deletion_in_bst.cpp
- Binary search tree/implement_part_2.cpp
- Binary search tree/implementation.cpp
added implementation and its various program code of binary search tree for participating in open source contribution of hactoberfest 2021
> added implementation and its various program code of binary search tree

- Dynamic Programming/Max_Sum_Inc_Subs.cpp
> Added the code of Maximum sum Inc Subsequnce

- graphs/bellmanFord.cpp
- It is used to find single source shortest path in Directed graph have negative edge but no negative cycle. Applicable for undirected graph as well but for positive edges as negative edge in undirected lead to cycle to itself.
- Time Complexity: O(n*e);
- The main intution behind it is , it try to relax edges (V-1) number of times and try to find shortest dist, if dist[src] + it's weight < dist[dest] then dist[dest] = dist[src]+weight
closes #47
> Bellman Ford in C++

- Sorting/WaveSort.cpp
> Wave sort using C++

- Sorting/max_heapsort.py
- graphs/Kruskals_algorithm.py
Kruskals algorithm and max heap sort
In kruskals algorithm I used disjoint sets.
Max heap sort in python
In this code I used max heap to sort the elements in ascending order
ISSUE NUMBER: #36
> Created Kruskals algorithm and  max_heapsort.py

- Dynamic Programming/longest_palindromic_subsequence.cpp
Dynamic Programming based C++ program for LPS problem
> Created longest_palindromic_subsequence.cpp

- Linked List/Java/LastToFront.java
- Linked List/Java/ReverseLinkedList.java
- String/Count.java
- String/Longest_subsequence.java
- array/JAVA/Move_neg_to_side.java
- array/JAVA/Sort_0_1_2.java
- graphs/Java/dijkstra.java
Contibuted to a good initiative of organising DSA fundamentals and code in one single position.
Hope it helps :)
> Added few of my DSA codes in Java.

- array/Sliding_Window/Bruteforce
> this the Brute force of maximum sum in k range in array

- array/Sliding_Window/Slidingwindowalogorithm.cpp
> optimised way to get the maximum sum in range of k in array

- Sorting/timsort.py
Timsort is a hybrid stable sorting algorithm, derived from merge sort and insertion sort, designed to perform well on many kinds of real-world data.
> creating pull request

- Sorting/shellsort.c
I just added the shell sort code here, that are able to sort an array.
> added shellsort.c

- Dynamic Programming/LongestCommonSubsequence.cpp
- Dynamic Programming/Unbounded_Knapsack.cpp
#61
DP Problem
longest common subsequence
> longest common subsequence using c++

- array/Dutch National Flag Algorithm/dutch-national-flag-algorithm.cpp
Opened PR corresponding to issue #57
> added dutch national flag algorithm in cpp

- Dynamic Programming/coin_change.cpp
> coin change dp problem

- Dynamic Programming/code subset_sum_dp.cpp
Given an array of non-negative integers and a value sum, determine if there is a subset of the given set with sum equal to given sum.
>  New code subset_sum_dp.cpp

- Linked List/detect_loop_linked_list.cpp
C++ program to return first node of loop
> Added detect_loop_linked_list.cpp

- stacks/prog1_push_and_pop.c
Have added stacks folder that is mentioned in the issues section. Also, I have included a program of stack performing push and pop.
> added stacks folder and wrote a program in it

- Sorting/insertionsort.py
Sorting/insertionsort.py added
Insertion sort script of python added with given data
> Insertion Sort added

- Dynamic Programming/longest_increasing_subsequence_dp.cpp
Bottom-Up DP solution of Longest Increasing Subsequence problem
> Created longest_increasing_subsequence_dp.cpp

- Searching/ternary-search.cpp
> Added ternary search implementation

- Dynamic Programming/Delete_operation_for_two_strings.cpp
583. Delete Operation for Two Strings
> delete operation for two string leetcode problem

- array/Hackerrank-Arrays -  Left Rotation.cpp
Please add hacktoberfest-accepted label too.
> Create Hackerrank-Arrays -  Left Rotation.cpp

- Searching/binarySearch.c
- Searching/linearSearch.c
/Searching/linearSearch.c
/Searching/binarySearch.c
**How it will work :** 
1)Enter the number of elements of the array
2)Enter the array numbers
3)Enter the number you want to find
(Binary Search will also sort the array )
_It will display the number position_
_if not found it will show Not found_
> Created linearSearch.c & binarySearch.c

- .vscode/c_cpp_properties.json
- .vscode/settings.json
- array/kth Largest element/kth-largest-element-in-array.cpp
solution to kth largest element in an array is added,
issue#51 solved
> kth largest element in array sol added

- Recursion/C and C++/Indirect Recursion.c
- Recursion/C and C++/Nested Recursion
- Recursion/C and C++/Sum of N natural numbers.c
- Recursion/C and C++/Taylor Series horner rule and iterative methods
- Recursion/C and C++/Tree Recursion
- Recursion/C and C++/factorial of a number.c
- Recursion/C and C++/fibonacci.c
- Recursion/C and C++/global variable recursion.c
- Recursion/C and C++/head Recursion.cpp
- Recursion/C and C++/power using recursion.c
- Recursion/C and C++/static variables Recursion.cpp
- Recursion/C and C++/tail recursion.cpp
I have checked all the codes twice, each of them is giving the correct output as per the question. 
I have made a C and C++ folder and added files inside that. 
Resolve issue #20
> I have added Questions based on Recursion solution using C and C++

- graphs/RangeQuerySegmentTree.cpp
Added code for Range Query with Segment Tree issue. resolves #73
> Range Query with Segment Tree

- Sorting/QuickSort.java
A easy to understand Java version of QuickSort Algorithm
Input is taken from the user and output is printed.
> Added java version of QuickSort

- array/Minimum number of Jumps To Reach End/minimum-number-of-jumps-to-reach-end.cpp
> added minimum jumps to reach end in cpp

- graphs/ConnectedComponents.cpp
Added Code for Connected Components in a graph. Resolve #56
> Connected Components in a graph

- mergeKsortLinklist.cpp
merge k sort linklist (bruteforce approach).
> MergeKsortLinklist

- array/Sorting and Searching/heapSort.cpp
This is my PR. Please review. Thanks
#4
> heapSort (CPP) array/sorting and searching

- MathematicsDS/eratosthenes_sieve.cpp
Program to find the prime numbers in O(nloglogn)
> Created eratosthenes_sieve.cpp

- Searching/Javascript/BinarySearch.js
Added BinarySearch in Javascript. This includes Iterative and Recursive approaches.
> Add: BinarySearch in Javascript: #159

- Dynamic Programming/MinimumNumberOfDeletionsAndInsertions.cpp
Solved #136 
(DP  Problem) 
minimum-number-of-deletions-and-insertions to transform str1 into str2
> MinimumNumberOfDeletionsAndInsertions using c++

- Bitmasks/Pairs in array of string.cpp
> Solved bitmask on array of string

- Dynamic Programming/DP- Target Sum
Time Complexity-O(N^2)
This is my code for https://leetcode.com/problems/target-sum/
> Create DP- Target Sum

- recursion/BinaryExponentiation.java
I have added Binary Exponentiation (Divide & conquer) code. 
This calculates exponents in O(logn) time complexity.
Kindly have a look.
> Added BinaryExponentiation.java

- Linked List/Remove Duplicate From Sorted List.cpp
Function for removing duplicate from linked list
problem Link - https://leetcode.com/problems/remove-duplicates-from-sorted-list/
> Create Remove Duplicate From Sorted List.cpp

- Matrix/Rotate matrix.cpp
LC. 48. Rotate Image #161 
You are given an n x n 2D matrix representing an image, rotate the image by 90 degrees (clockwise).
You have to rotate the image in-place, which means you have to modify the input 2D matrix directly. DO NOT allocate another 2D matrix and do the rotation.
> added rotate matrix problem

- array/Sorting and Searching/binarySearch.c
- array/Sorting and Searching/linearSearch.c
\array\Sorting and Searching\linearSearch.c
\array\Sorting and Searching\binarySearch.c
Added linearSearch.c in array folder
Added binarySearch.c in array folder
**How to use :**
1) enter the no. of elements of array
2) enter the array elements
(array will be sorted automatically if needed)
3) enter the element you want to find
_If present it will display the element position_
_If not present it will display "Not Present"_
> linearSearch.c and binarySearch.c added

- MathematicsDS/SieveOfErastosthenes.cpp
Please review and merge the code.
> added sieve of Eratosthenes

- Stack/MaxRectangle.cpp
Added the code for Max area Rectangle.
> Added Max Area Rectangle.

- graphs/SingleCycleinGraph.cpp
- graphs/TraversingGridUsingdfs.cpp
Added codes for "Print a single cycle in a graph" and "Traversing a grid using dfs".
closes #77 closes #79
> Added codes for issues #77 and #79

- Searching/search_element_in_row_column_sorted_matrix.cpp
CPP Code to search an element in row-wise and column-wise sorted matrix
> Created search_element_in_row_column_sorted_matrix.cpp

- MathematicsDS/returngift.cpp
- MathematicsDS/separateno.cpp
Retun Gift -1(A prime no problem)
> Retun Gift -1

- String/naive_pattern_searching.cpp
> added naive pattern searching algorithm in c++

- BST/bst.cpp
Added own approach for implementing BST in CPP without the use of STL.
> Added My Own BST Program without STL

- Dynamic Programming/LongestRepeatingSubsequence.cpp
Issue #135 
(DP Problem)
Longest repeating subsequence
> Longest repeating subsequence using c++

- Matrix/matrix_addition
Implementing matrix addition in C++
> Matrix addition in c++

- Tree/Top_view_binary_tree.cpp
Added a cpp program to print top view of a binary tree
> Added a cpp program to print top view of a binary tree

- String/Time_conversion.cpp
This cpp code converts the time given in 12-hour AM/PM format into military time format (24 hours ).
> Time conversion code

- Linked List/Python/mergesort_for_linkedlist.py
Added merge sort algo for linked list in python.
> merge sort for linked list

- Linked List/Python/mergesort_for_linkedlist.py
- graphs/python/bfs.py
- graphs/python/dfs.py
- graphs/python/topologicalsort.py
Added bfs, dfs, topological sort for graph in python.
> Graph Algos in Python

- huffmancoding.cpp
It is a technique of compressing data to reduce its size without losing any of the details.
> Huffmancoding

- Tree/LCA_of_Binary_Tree.cpp
Lowest Commn Ancestor of a Binary Tree
> LCA of a Binary Tree

- Kotlin/InsertionSort.kt
Please add my file to your repo with label Hacktoberfest
> InsertionSort.kt 

- Dynamic Programming/Sieve_of_Eratosthenes.java
- Important cpp codes/fastPower2.java
- Recursion/Java/Josephus.java
> Sieve_Of_Eratosthenes

- Bit manipulation/set-mismatch.java
added bit manipulation problem leetcode #645. Set Mismatch.java
> added set-mismatch.java problem

- LeetCode/Pascal's Triangle - 118/README.md
- LeetCode/Pascal's Triangle - 118/pascals-triangle.cpp
Provided solution for <a href="https://leetcode.com/problems/pascals-triangle/">118. Pascal's Triangle</a>
Language Used: C++
> Added Leetcode-118-pascal-triangle solution

- SieveOfEratosthenes.py
- shortestpathundirectedgraph.cpp
Added 2 more algorithms
1. SieveOfEratosthenes
2. Shortest Path in Undirected Graph
> Shortest Path in Undirected Graph &  SieveOfEratosthenes

- stacks/224. Basic Calculator
This might be a standard question of Stack, i guess it must be in this repo.
Thank You.
> Create 224. Basic Calculator

- array/spiralPrintOf2Darray.cpp
solution of spiral print of 2d array is added
> Spiral Print of a 2D array

- 15-puzzle.cpp
Added the famous 15 puzzle solver algorithm that uses branch and bound technique.
Output looks like this
> Add 15 puzzle solver algorithm

- ProjectEuler/3.py
- ProjectEuler/4.py
Hi, please accept for hacktoberfest22
> Added Solution to Problem 3 of Project Euler

- cses/apartments.cpp
- cses/array-description.cpp
https://cses.fi/problemset/task/1746
> Cses array description

- cses/apartments.cpp
Add the solution to the Apartments problem in the CSES problemset
https://cses.fi/problemset/task/1084
> Add CSES apartments solution

- cses/apartments.cpp
- cses/array-description.cpp
- cses/bit_strings.cpp
https://cses.fi/problemset/task/1617
> Cses bit strings

- Linked List/Reverse_nodes_in_k_groups.cpp
Example 1:
Input: head = [1,2,3,4,5], k = 2
Output: [2,1,4,3,5]
Example 2:
Input: head = [1,2,3,4,5], k = 3
Output: [3,2,1,4,5]
> code to reverse nodes in k groups

- Dynamic Programming/Dynamic Programming/Longest_Palindromic_Substring.cpp
Example 1:
Input: s = "babad"
Output: "bab"
Explanation: "aba" is also a valid answer.
Example 2:
Input: s = "cbbd"
Output: "bb"
> code for longest palindromic substring

- Sorting/bubbleSort.cpp
> Hacktoberfest2022 bubbleSort.cpp

- quicksort.java
quicksort technique using java
> quicksort in java

- String/autoPasswordGenerator.cpp
Program on Strings, to automatically generate passwords
> Added program on auto password generation

- LeetCode/1289. Minimum Falling Path Sum II.java
> 1289. Minimum Falling Path Sum II

- Interview Questions/Amazon/Medium.txt
Added medium level interview questions for amazon along with answers
> Added Amazon Medium level DSA Interview Questions
